version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariano
      MYSQL_DATABASE: posts
      MYSQL_USER: root
      MYSQL_PASSWORD: mariano 